### ISSUE TITLE
Request for type hints support in replicate-python

### ISSUE THREAD

**Issue by ferdousbhai** [replicate/replicate-python#124]
I would like to request type hints support for the library. 🙏🏽

**Comment by mattt** [comment]
Hi @ferdousbhai. The Python library has type hints, for example:

https://github.com/replicate/replicate-python/blob/52979a656c9b1aef0ece340dba0dc48b81fa6ba8/replicate/prediction.py#L73-L81

We run `mypy` and `ruff` in CI to verify that type annotations are correct and cover the whole codebase (excluding tests).

**Comment by WAKayser** [comment]
Mypy needs an extra py.typed marker so that it can quickly check if the the package is ready for type checking. (See PEP 561).

If you want to have this already available before this is added to the package, then this can also be done manually by adding this file to the replicate folder in your site-packages.

**Comment by mattt** [comment]
@WAKayser Thanks, TIL. I just opened a PR for this here: https://github.com/replicate/replicate-python/pull/127
