### ISSUE TITLE
"Exception: Can't create Version from next"

### ISSUE THREAD

**Issue by afiaka87** [replicate/replicate-python#15]
Was trying to use the package to run my `afiaka87/pyglide` demo and got this error. Digging through the code, it appears to be a known issue perhaps, as I'm seeing lots of "# TODO - might be a list" around the stack-trace.

to recreate:
```python
model_name = "afiaka87/pyglide"
model = replicate.models.get(model_name)
version = model.versions.list()[0]
```

**Comment by afiaka87** [comment]
Ah, apologies - appears it was a change in the API and has been fixed already: 

https://github.com/replicate/replicate-python/issues/13

**Comment by bfirsh** [comment]
Yes please upgrade! Sorry. 😄

I'll leave this open for a bit for visibility.

**Comment by zeke** [comment]
Has there been a release to PyPi since #13 landed?

Looking at the [CI workflow](https://github.com/replicate/replicate-python/blob/ab4439ee02d1f157cd3b904f5e0232b69bbae707/.github/workflows/ci.yaml#L60), it appears the release process is to manually push a git tag, like we do for [publishing Cog releases](https://github.com/replicate/cog/blob/498fe29633ed0dda27941cdb412ec56a99ee8a3c/CONTRIBUTING.md#publishing-a-release). Is that right, @bfirsh?

**Comment by bfirsh** [comment]
Yep, that's right. Release process is currently "Ben does it" and I realize that is not scalable. Feel free to document the correct process. ;)

**Comment by bfirsh** [comment]
I have also done a release of this.

**Comment by zeke** [comment]
Looks like there's [no git tag for 0.0.1a7](https://github.com/replicate/replicate-python/tags), so no release. See https://github.com/replicate/replicate-python/actions

<img width="640" alt="Screen Shot 2022-05-19 at 1 54 44 PM" src="https://user-images.githubusercontent.com/2289/169403096-354b3d38-fef1-4bce-83c3-8d86ec1f596b.png">

**Comment by bfirsh** [comment]
oops pebkac

**Comment by zeke** [comment]
No worries. I now see the tag on GitHub and the new release on PyPI, and my unchanged code is working again.

Closing! 🤘🏼
