### ISSUE TITLE
Progress log of image generation not working 

### ISSUE THREAD

**Issue by 921kiyo** [replicate/replicate-python#171]
There was a discussion in  https://github.com/replicate/replicate-python/issues/152 that Prediction class instance now provides progress information. But I don't thinks it's working as expected. Could you please have a look at this and confirm that `progress` property is always available for `Prediction` instance?

Also there used to progress info in the log property of Prediction class instance, but I don't get this anymore (I was relying on this to check the progress in our UI)

**Comment by mattt** [comment]
Hey @921kiyo. Sorry for not responding to #152. 

The way progress is determined is by scanning the prediction logs and scanning for output in a given pattern. If the logs aren't present or not in the right format, the progress property will return `None`.

In a recent issue over on the JS client (https://github.com/replicate/replicate-javascript/issues/146#issuecomment-1762144306), someone was reporting a similar issue with their mode, and it turned out to be an issue with logs not populating for their predictions. That was also a fine-tune of SDXL. That issue appeared to be resolved, but perhaps it's come up again. I'll ask around to see what's going on.

**Comment by mattt** [comment]
Following up on this —

I believe the issue of logs populating for in-flight predictions should now be resolved Please let me know if you're still having issues with prediction logs, and I'd be happy to take a look for Replicate's platform. But for now, I'll go ahead and close this issue, since there's nothing actionable here as far as the client library is concerned.
