### ISSUE TITLE
cannot import name 'JSONDecodeError' from 'json'

### ISSUE THREAD

**Issue by nagolinc** [replicate/replicate-python#38]
importing replicate fails

```[root@ip-172-31-18-88 replicate]# python3
Python 3.7.9 (default, Aug 27 2020, 21:59:41)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import replicate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/replicate/__init__.py", line 2, in <module>
    from .client import Client
  File "/usr/local/lib/python3.7/site-packages/replicate/client.py", line 2, in <module>
    from json import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'json' (/home/ec2-user/.local/lib/python3.7/site-packages/replicate/json.py)
```

**Comment by bfirsh** [comment]
Hmm, interesting. Your Python is import `replicate.json` instead of `json`. Perhaps because [absolute imports](https://stackoverflow.com/questions/6031584/importing-from-builtin-library-when-module-with-same-name-exists) are disabled for some reason.

Have you explicitly disabled absolute imports, or something? Maybe it's a red hat thing? Unsure.

**Comment by nagolinc** [comment]
Huh.  Must have screwed up the install somehow.  deleted /home/ec2-user/.local/lib/python3.7/site-packages/replicate/ and then  python3 -m pip install replicate --force-reinstall seems to have fixed it

**Comment by bfirsh** [comment]
Weird. Glad you sort it!
